name: polymarket

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: polymarket-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "127.0.0.1:1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: